//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPRequestScheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTTPRequestScheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliable Parameters:
        ///
        ///  Headers         =&gt; Line per each header in this format: &apos;header1=value1\r\nheader2=value2&apos;
        ///  RequestType     =&gt; GET / POST / PUT / HEAD / DELETE / PATCH / OPTIONS
        ///  RequestUrl      =&gt; Request URL
        ///  Content         =&gt; Content to send with the request (For POST and PUT requests)
        ///  ContentType     =&gt; e.g. application/json or text/plain
        ///  ExcelFile       =&gt; Location of the Workbook (.\FileName.xlsx for file on the same path of the exe)
        ///  SheetName       =&gt; Sheet on the excel fil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string arguments {
            get {
                return ResourceManager.GetString("arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers=
        ///RequestType=GET
        ///RequestUrl=
        ///Content=
        ///ContentType=application/json
        ///Delay=0
        ///ExcelFile=.\Workbook.xlsx
        ///SheetName=
        ///FirstRow=1
        ///RecursiveInsert=True
        ///Trigger=False
        ///Days=All
        ///Time=04:00.
        /// </summary>
        internal static string DefaultIni {
            get {
                return ResourceManager.GetString("DefaultIni", resourceCulture);
            }
        }
    }
}
